# -*- coding: utf-8 -*-
"""
YAML service — read/write/migrate RUN files in YAML format.

Design (Option B): YAML is the human-editable source of truth.
    RUN_*.yaml  ← edited by user (and soon by the GUI)
    RUN_*.py    ← auto-generated by generate_py_from_yaml(); never manually edited

Main public API
───────────────
    load_yaml_run(path)          → info dict  (same shape as _build_run_info)
    get_yaml_flow(path)          → flow dict  (same shape as get_run_flow)
    generate_py_from_yaml(path)  → write RUN_*.py next to the .yaml
    migrate_py_to_yaml(path)     → write RUN_*.yaml next to the .py (migration)
    validate_yaml_doc(doc)       → list[str] of errors (empty = ok)

YAML schema (canonical)
───────────────────────
    project_folder: "C:/path/to/film"

    defaults:
      backend: linux
      fps: 16
      steps: 6
      cfg: 2.0
      blocks_to_swap: 35
      resolution: [1024, 1024]   # becomes FORCE_RESOLUTION; null = auto
      duration: 2
      skip_existed: true

    use_test_flow: false

    flow:                        # = FLOW_FULL
      - file: "frame.png"
        duration: 5
        pos: |
          Smooth cinematic zoom...
        neg: "blurry, low quality"

      - break: true

      - chain:
          prefix: my_chain
          fps: 16
          steps: 6
          cfg: 2.0
          neg: "static, frozen"
          transitions:           # ← chosen name for chain step list
            - duration: 3
              pos: |
                Step 1 prompt...
            - duration: 3
              pos: |
                Step 2 prompt...

    flow_test:                   # = FLOW_TEST (optional)
      - file: "test.png"
        duration: 2
        pos: "NONE"
        neg: "blurry"
"""

from __future__ import annotations

import textwrap
from datetime import datetime
from pathlib import Path
from typing import Any

import yaml

from app.services import app_config_service
from app.services.run_file_service import (
    RUNS_FOLDER,
    extract_globals,
    make_display_name,
)


# ============================================================
# Validation
# ============================================================

def _check_flow_item(item: Any, idx: int) -> list[str]:
    errors: list[str] = []
    if not isinstance(item, dict):
        return [f"flow[{idx}]: must be a mapping, got {type(item).__name__}"]
    if item.get("break"):
        return []
    if "header" in item:
        return []  # header items are display-only, always valid
    if item.get("type") == "scene_break":
        return []  # scene_break items are always valid
    if item.get("type") == "multichain":
        chain = item.get("chain")
        if not isinstance(chain, list) or len(chain) == 0:
            errors.append(f"flow[{idx}].multichain: 'chain' must be a non-empty list")
        return errors
    if "chain" in item:
        chain = item["chain"]
        if not isinstance(chain, dict):
            errors.append(f"flow[{idx}].chain: must be a mapping")
            return errors
        t = chain.get("transitions")
        if t is None:
            errors.append(f"flow[{idx}].chain: missing 'transitions' list")
        elif not isinstance(t, list) or len(t) == 0:
            errors.append(f"flow[{idx}].chain: 'transitions' must be a non-empty list")
        return errors
    if item.get("type") == "talk":
        audio = item.get("audio")
        if audio is None:
            errors.append(f"flow[{idx}].talk: 'audio' is required")
        elif isinstance(audio, dict):
            # Single entry as dict: {file, pos, neg}
            if not audio.get("file"):
                errors.append(f"flow[{idx}].talk: audio dict must have 'file'")
        elif isinstance(audio, str):
            pass  # plain filename — OK
        elif isinstance(audio, list):
            if len(audio) == 0:
                errors.append(f"flow[{idx}].talk: 'audio' list must not be empty")
            else:
                for ei, entry in enumerate(audio):
                    if isinstance(entry, str):
                        pass  # plain filename — OK
                    elif isinstance(entry, dict):
                        if not entry.get("file"):
                            errors.append(
                                f"flow[{idx}].talk: audio[{ei}] dict must have 'file'"
                            )
                    else:
                        errors.append(
                            f"flow[{idx}].talk: audio[{ei}] must be a filename or dict"
                        )
        else:
            errors.append(f"flow[{idx}].talk: 'audio' must be a string, dict, or list")
        return errors
    if item.get("type") == "multitalk":
        return errors
    if item.get("type") == "dubit":
        return errors
    if "file" not in item:
        errors.append(f"flow[{idx}]: must have 'file', 'break', 'chain', or 'type: talk/multitalk/dubit'")
    return errors


def validate_yaml_doc(doc: Any) -> list[str]:
    """Validate a parsed YAML document. Returns list of error strings."""
    errors: list[str] = []
    if not isinstance(doc, dict):
        return ["Document must be a YAML mapping"]
    if not doc.get("project_folder"):
        errors.append("'project_folder' is required")
    flow = doc.get("flow")
    if flow is None:
        errors.append("'flow' list is required")
    elif not isinstance(flow, list):
        errors.append("'flow' must be a list")
    else:
        for i, item in enumerate(flow):
            errors.extend(_check_flow_item(item, i))
    flow_test = doc.get("flow_test")
    if flow_test is not None:
        if not isinstance(flow_test, list):
            errors.append("'flow_test' must be a list")
        else:
            for i, item in enumerate(flow_test):
                errors.extend(_check_flow_item(item, i))
    return errors


# ============================================================
# Format conversion: YAML flow ↔ internal flow
# ============================================================

def _yaml_item_to_internal(item: dict) -> dict:
    """
    Convert a single YAML flow item to the internal format used by the app.

    YAML chain format:
        {"chain": {"prefix": "name", "transitions": [...], "fps": 16, ...}}

    Internal chain format (matches what batch_transitions.py expects):
        {"chain": [...steps...], "chain_prefix": "name", "fps": 16, ...}

    YAML talk format:
        {"type": "talk", "audio": "voice.mp3", "width": 480, "height": 832, ...}

    Internal talk format: same dict, passed through verbatim.
    """
    if item.get("break"):
        result = {"break": True}
        if item.get("label"):
            result["label"] = item["label"]
        return result
    if item.get("type") == "scene_break":
        return {"type": "scene_break", "name": item.get("name", "")}
    if "header" in item:
        return {"header": item["header"]}
    if item.get("type") == "multichain":
        # Pass through verbatim — same as talk/multitalk/dubit, no dict/list reshaping
        return dict(item)
    if "chain" in item:
        chain_data = item["chain"]
        if not isinstance(chain_data, dict):
            return item
        transitions = chain_data.get("transitions", [])
        result: dict[str, Any] = {
            "chain":        transitions,
            "chain_prefix": chain_data.get("prefix", "chain"),
        }
        for k in ("backend", "duration", "fps", "steps", "cfg", "neg", "blocks_to_swap", "width", "height", "frame_interpolation", "use_lightning", "atlascloud_resolution", "atlascloud_prompt_extend"):
            if k in chain_data and chain_data[k] is not None:
                result[k] = chain_data[k]
        return result
    if item.get("type") == "talk":
        # Pass through verbatim — all fields (audio, width, height, pos) preserved
        return dict(item)
    # Regular file item — copy verbatim
    return dict(item)


def _internal_item_to_yaml(item: dict) -> dict:
    """
    Convert a single internal flow item back to YAML format.
    Inverse of _yaml_item_to_internal().
    """
    if item.get("break"):
        result = {"break": True}
        if item.get("label"):
            result["label"] = item["label"]
        return result
    if item.get("type") == "scene_break":
        return {"type": "scene_break", "name": item.get("name", "")}
    if "header" in item:
        return {"header": item["header"]}
    if item.get("type") == "multichain":
        # Pass through verbatim — same as talk/multitalk/dubit, no dict/list reshaping
        return dict(item)
    if "chain" in item:
        chain_prefix = item.get("chain_prefix", "chain")
        chain_data: dict[str, Any] = {
            "prefix":      chain_prefix,
            "transitions": item.get("chain", []),
        }
        for k in ("backend", "duration", "fps", "steps", "cfg", "neg", "blocks_to_swap", "width", "height", "frame_interpolation", "use_lightning", "atlascloud_resolution", "atlascloud_prompt_extend"):
            if k in item and item[k] is not None:
                chain_data[k] = item[k]
        return {"chain": chain_data}
    if item.get("type") == "talk":
        # Pass through verbatim
        return dict(item)
    return dict(item)


def yaml_flow_to_internal(yaml_flow: list) -> list[dict]:
    """Convert a YAML 'flow' list to internal format."""
    return [_yaml_item_to_internal(item) for item in yaml_flow if isinstance(item, dict)]


def internal_flow_to_yaml(internal_flow: list) -> list:
    """Convert internal flow list to YAML-format list."""
    return [_internal_item_to_yaml(item) for item in internal_flow if isinstance(item, dict)]


# ============================================================
# Load YAML RUN file → info dict (same shape as _build_run_info)
# ============================================================

def load_yaml_run(yaml_path: Path) -> dict | None:
    """
    Load and parse a YAML RUN file.
    Returns the same info-dict shape as run_file_service._build_run_info().
    Returns None if the file does not exist.
    Errors are stored in the 'error' key.
    """
    if not yaml_path.exists():
        return None

    # Use a pseudo-.py name for display_name so the helper works
    display_stem = yaml_path.stem  # e.g. "RUN_011_praca_w_postapo"
    info: dict[str, Any] = {
        "filename":              yaml_path.name,
        "display_name":          make_display_name(display_stem + ".py"),
        "compatibility":         "yaml",
        "project_folder":        None,
        "force_resolution":      None,
        "default_resolution":    None,
        "default_backend":       None,
        "default_blocks_to_swap":      None,
        "default_fps":                 None,
        "default_steps":               None,
        "default_frame_interpolation": None,
        "error":                       None,
        "source":                "yaml",
    }

    try:
        content = yaml_path.read_text(encoding="utf-8")
    except OSError as e:
        info["error"] = str(e)
        return info

    try:
        doc = yaml.safe_load(content)
    except yaml.YAMLError as e:
        mark = getattr(e, 'problem_mark', None)
        info["error"] = f"YAML parse error: {e}"
        info["syntax_error"] = {
            "msg":    getattr(e, 'problem', str(e)),
            "line":   (mark.line + 1) if mark else None,
            "offset": (mark.column + 1) if mark else None,
            "text":   (mark.get_snippet() if (mark and hasattr(mark, 'get_snippet')) else None),
        }
        return info

    errors = validate_yaml_doc(doc)
    if errors:
        info["error"] = "; ".join(errors)
        return info

    defs = doc.get("defaults") or {}
    res = defs.get("resolution")
    info["project_folder"]         = doc.get("project_folder")
    info["force_resolution"]       = tuple(res) if res else None
    info["default_resolution"]     = tuple(res) if res else None
    info["default_backend"]              = defs.get("backend", "linux")
    info["default_blocks_to_swap"]      = defs.get("blocks_to_swap")
    info["default_fps"]                 = defs.get("fps")
    info["default_steps"]               = defs.get("steps")
    info["default_frame_interpolation"] = defs.get("frame_interpolation")

    return info


# ============================================================
# Load YAML flow → flow dict (same shape as get_run_flow)
# ============================================================

def get_yaml_flow(yaml_path: Path) -> dict | None:
    """
    Extract flow data from a YAML RUN file.
    Returns the same dict shape as run_file_service.get_run_flow().
    """
    if not yaml_path.exists():
        return None

    try:
        doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    except Exception:
        return None

    if not isinstance(doc, dict):
        return None

    use_test = bool(doc.get("use_test_flow", False))
    has_full = isinstance(doc.get("flow"), list)
    has_test = isinstance(doc.get("flow_test"), list)

    if use_test and has_test:
        raw, flow_type = doc["flow_test"], "test"
    elif has_full:
        raw, flow_type = doc["flow"], "full"
    elif has_test:
        raw, flow_type = doc["flow_test"], "test"
    else:
        return None

    flow = yaml_flow_to_internal(raw)

    return {
        "flow":          flow,
        "flow_type":     flow_type,
        "use_test":      use_test,
        "has_test_flow": has_test,
        "has_full_flow": has_full,
        "item_count":    len(flow),
    }


# ============================================================
# Python code generator: YAML → .py
# ============================================================

def _py_val(val: Any, indent: int = 0) -> str:
    """Recursively format a Python value as valid Python source code."""
    pad = " " * indent

    if val is None:
        return "None"
    if isinstance(val, bool):
        return "True" if val else "False"
    if isinstance(val, (int, float)):
        return repr(val)
    if isinstance(val, str):
        if "\n" in val:
            # Use triple-quoted string; escape any existing triple-quotes
            escaped = val.replace('"""', r'\"\"\"')
            # Strip trailing whitespace on each line to keep .py clean
            lines = [line.rstrip() for line in escaped.split("\n")]
            body = "\n".join(lines)
            return f'"""{body}"""'
        return repr(val)
    if isinstance(val, (list, tuple)):
        if not val:
            return "[]" if isinstance(val, list) else "()"
        inner_indent = indent + 4
        items = [" " * inner_indent + _py_val(v, inner_indent) for v in val]
        inner = ",\n".join(items)
        o, c = ("[", "]") if isinstance(val, list) else ("(", ")")
        return f"{o}\n{inner},\n{pad}{c}"
    if isinstance(val, dict):
        if not val:
            return "{}"
        inner_indent = indent + 4
        items = [
            " " * inner_indent + repr(k) + ": " + _py_val(v, inner_indent)
            for k, v in val.items()
        ]
        inner = ",\n".join(items)
        return f"{{\n{inner},\n{pad}}}"
    return repr(val)


def _flow_list_to_py(flow: list, var_name: str) -> str:
    """Render a flow list as a Python assignment: VAR_NAME = [...]."""
    if not flow:
        return f"{var_name} = []\n"

    lines = [f"{var_name} = ["]
    for item in flow:
        if not isinstance(item, dict):
            continue
        if item.get("break"):
            lines.append('    {"break": True},')
            lines.append("")
            continue
        if "header" in item:
            header_text = str(item["header"])
            bar = "─" * max(4, 54 - len(header_text) - 2)
            lines.append(f"")
            lines.append(f"    # ── {header_text} {bar}")
            continue
        if item.get("type") == "multichain":
            # multichain item — render as plain dict, verbatim (same as talk/multitalk)
            lines.append("    {")
            for k, v in item.items():
                vr = _py_val(v, 8)
                lines.append(f'        {repr(k)}: {vr},')
            lines.append("    },")
            lines.append("")
            continue
        if "chain" in item:
            # chain item — keep internal format (what batch_transitions expects)
            chain_steps = item.get("chain", [])
            chain_prefix = item.get("chain_prefix", "chain")
            lines.append("    {")
            lines.append('        "chain": [')
            for step in chain_steps:
                lines.append("            {")
                for k, v in step.items():
                    vr = _py_val(v, 16)
                    lines.append(f'                {repr(k)}: {vr},')
                lines.append("            },")
            lines.append("        ],")
            lines.append(f'        "chain_prefix": {repr(chain_prefix)},')
            for k in ("backend", "duration", "fps", "steps", "cfg", "neg", "blocks_to_swap", "width", "height", "frame_interpolation", "use_lightning", "atlascloud_resolution", "atlascloud_prompt_extend"):
                if k in item:
                    vr = _py_val(item[k], 8)
                    lines.append(f'        {repr(k)}: {vr},')
            lines.append("    },")
            lines.append("")
            continue
        if item.get("type") in ("talk", "multitalk"):
            # talk/multitalk items — render as plain dict
            lines.append("    {")
            for k, v in item.items():
                vr = _py_val(v, 8)
                lines.append(f'        {repr(k)}: {vr},')
            lines.append("    },")
            lines.append("")
            continue
        # Regular file item
        lines.append("    {")
        for k, v in item.items():
            vr = _py_val(v, 8)
            lines.append(f'        {repr(k)}: {vr},')
        lines.append("    },")
    lines.append("]")
    return "\n".join(lines) + "\n"


_PY_HEADER = '''\
# -*- coding: utf-8 -*-
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# AUTO-GENERATED — do NOT edit manually.
# Edit {yaml_name} and regenerate with:
#     from app.services.yaml_service import generate_py_from_yaml
#     generate_py_from_yaml(Path("RUNS/{yaml_name}"))
# Generated: {timestamp}
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent))

from config_validator import validate_config_or_exit
from batch_transitions import run_batch_generation

# ============================================================
# PROJECT CONFIG
# ============================================================

PROJECT_FOLDER = {project_folder}

'''

_PY_FOOTER = '''\

# ============================================================
# RUN
# ============================================================

if __name__ == "__main__":
    config = validate_config_or_exit(globals())
    run_batch_generation(config)
'''


def generate_py_from_yaml(yaml_path: Path, out_path: Path | None = None) -> Path:
    """
    Generate a RUN_*.py file from a RUN_*.yaml file.

    Parameters
    ----------
    yaml_path : Path
        Path to the source .yaml file.
    out_path : Path | None
        Destination .py path.  Defaults to same dir/stem as yaml_path but .py.

    Returns
    -------
    Path
        Path to the written .py file.

    Raises
    ------
    ValueError
        If the YAML document fails validation.
    FileNotFoundError
        If yaml_path does not exist.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    errors = validate_yaml_doc(doc)
    if errors:
        raise ValueError("YAML validation errors:\n" + "\n".join(f"  • {e}" for e in errors))

    if out_path is None:
        out_path = yaml_path.with_suffix(".py")

    # defaults: per-project overrides app_config, app_config overrides hard-coded
    _app_defs = app_config_service.get_defaults()
    defs      = {**_app_defs, **(doc.get("defaults") or {})}

    # ── Build file sections ──────────────────────────────────────────
    parts: list[str] = []

    # Header + PROJECT_FOLDER
    parts.append(_PY_HEADER.format(
        yaml_name=yaml_path.name,
        timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        project_folder=repr(str(doc["project_folder"])),
    ))

    # Resolution
    res = defs.get("resolution")
    if res:
        parts.append(f"FORCE_RESOLUTION = {_py_val(tuple(res))}\n")
        parts.append(f"DEFAULT_RESOLUTION = {_py_val(tuple(res))}\n")
    else:
        parts.append("FORCE_RESOLUTION = None\n")
        parts.append("DEFAULT_RESOLUTION = (1024, 1024)\n")

    # Default generation settings
    parts.append(f"\nDEFAULT_BACKEND        = {repr(defs.get('backend', 'linux'))}\n")
    parts.append(f"DEFAULT_FPS            = {defs.get('fps', 16)}\n")
    parts.append(f"DEFAULT_STEPS          = {defs.get('steps', 6)}\n")
    parts.append(f"DEFAULT_CFG            = {defs.get('cfg', 2.0)}\n")
    parts.append(f"DEFAULT_DURATION       = {defs.get('duration', 2)}\n")
    parts.append(f"DEFAULT_BLOCKS_TO_SWAP      = {defs.get('blocks_to_swap', 35)}\n")
    _fi = defs.get('frame_interpolation')
    _fi_val = "True" if _fi is None or _fi else "False"
    parts.append(f"DEFAULT_FRAME_INTERPOLATION = {_fi_val}\n")
    _pos_prompt = defs.get('default_positive_prompt', '') or "smooth motion, high quality, cinematic"
    parts.append(f"DEFAULT_POSITIVE_PROMPT = {repr(str(_pos_prompt))}\n")
    _neg_prompt = defs.get('default_negative_prompt', '') or "blurry, distorted, artifacts, watermark, text"
    parts.append(f"DEFAULT_NEGATIVE_PROMPT = {repr(str(_neg_prompt))}\n")
    _audio_prompt = defs.get('default_audio_prompt', '') or "ambient sound, environmental audio, natural soundscape, high quality"
    parts.append(f"DEFAULT_AUDIO_PROMPT   = {repr(str(_audio_prompt))}\n")
    _audio_neg_prompt = defs.get('default_audio_negative_prompt', '') or "music, melody, instruments, singing, low quality, distortion"
    parts.append(f"DEFAULT_AUDIO_NEGATIVE_PROMPT = {repr(str(_audio_neg_prompt))}\n")
    parts.append(f"DEFAULT_SEED           = None\n")
    parts.append(f"SKIP_MISSING           = True\n")
    parts.append(f"SKIP_EXISTED           = {_py_val(defs.get('skip_existed', True))}\n")
    parts.append(f"IMAGE_QUALITY          = 95\n")
    parts.append(f"ASPECT_RATIO_TOLERANCE = 0.13\n")
    parts.append(f"ASPECT_RATIO_STRATEGY  = 'most_common'\n")
    parts.append(f"DEBUG_LOG              = True\n")

    # Postprocessing — disabled by default (not yet in YAML schema)
    parts.append("\nPOSTPROCESSING = {'enabled': False}\n")

    # Linux backend paths
    # Priority: per-project linux_backend → app_config.yaml backends.linux + models.video_gen
    _app_lb   = app_config_service.get_backend("linux")
    _app_vgen = app_config_service.get_model("linux", "video_gen")
    lb        = doc.get("linux_backend") or {}

    def _lb(yaml_key: str, app_key: str | None = None) -> str | None:
        """Return per-project value, else app_config value, else None."""
        v = lb.get(yaml_key)
        if v:
            return str(v)
        k = app_key or yaml_key
        v = _app_lb.get(k)
        return str(v) if v else None

    _lb_values = {
        "CONFIG_PATH":           lb.get("config_path")           or _app_vgen.get("config_path"),
        "WORKFLOWS_PATH":        lb.get("workflows_path")        or _app_lb.get("workflows_path"),
        "COMFYUI_OUTPUT_FOLDER": lb.get("comfyui_output_folder") or _app_lb.get("comfyui_output_folder"),
        "API_URL":               lb.get("api_url")               or _app_lb.get("api_url"),
    }
    if any(_lb_values.values()):
        parts.append("\n# ── Linux backend paths ─────────────────────────────────────────\n")
        for py_key, v in _lb_values.items():
            if v:
                parts.append(f"{py_key} = {repr(str(v))}\n")

    # USE_TEST_FLOW
    use_test = bool(doc.get("use_test_flow", False))
    parts.append(f"\nUSE_TEST_FLOW = {_py_val(use_test)}\n")

    # FLOW_FULL
    parts.append("\n# ============================================================\n")
    parts.append("# FLOW\n")
    parts.append("# ============================================================\n\n")

    full_flow_yaml = doc.get("flow", [])
    full_flow_internal = yaml_flow_to_internal(full_flow_yaml)
    parts.append(_flow_list_to_py(full_flow_internal, "FLOW_FULL"))

    # FLOW_TEST (optional)
    test_flow_yaml = doc.get("flow_test")
    if test_flow_yaml is not None:
        parts.append("\n")
        test_flow_internal = yaml_flow_to_internal(test_flow_yaml)
        parts.append(_flow_list_to_py(test_flow_internal, "FLOW_TEST"))

    # Active FLOW selector
    if test_flow_yaml is not None:
        parts.append("\nFLOW = FLOW_TEST if USE_TEST_FLOW else FLOW_FULL\n")
    else:
        parts.append("\nFLOW = FLOW_FULL\n")

    # Footer
    parts.append(_PY_FOOTER)

    out_path.write_text("".join(parts), encoding="utf-8")
    return out_path


# ============================================================
# Migration: .py → .yaml
# ============================================================

# Keys that are redundant / internal and should not appear in YAML
_SKIP_KEYS = {
    "FLOW", "FLOW_FULL", "FLOW_TEST",
    "USE_TEST_FLOW", "PROJECT_FOLDER",
    "FORCE_RESOLUTION", "DEFAULT_RESOLUTION",
    "DEFAULT_BACKEND", "DEFAULT_FPS", "DEFAULT_STEPS", "DEFAULT_CFG",
    "DEFAULT_DURATION", "DEFAULT_BLOCKS_TO_SWAP", "DEFAULT_SEED",
    "SKIP_MISSING", "SKIP_EXISTED", "IMAGE_QUALITY",
    "ASPECT_RATIO_TOLERANCE", "ASPECT_RATIO_STRATEGY",
    "MIN_WIDTH", "MIN_HEIGHT", "MAX_WIDTH", "MAX_HEIGHT",
    "DEFAULT_POSITIVE_PROMPT", "DEFAULT_NEGATIVE_PROMPT",
    "DEFAULT_AUDIO_PROMPT", "DEFAULT_AUDIO_NEGATIVE_PROMPT",
    "GENERIC_PROMPTS", "POSTPROCESSING", "DEBUG_LOG",
    # cloud backend — kept separately
    "COMFY_ICU_WORKFLOW_ID", "WORKFLOW_TEMPLATE_PATH",
    # linux backend paths — now stored in 'linux_backend:' YAML section (optional per-project override)
    "CONFIG_PATH", "WORKFLOWS_PATH", "COMFYUI_OUTPUT_FOLDER", "API_URL",
}


def _get_both_flows(py_path: Path) -> tuple[list | None, list | None]:
    """
    Return (FLOW_FULL, FLOW_TEST) from a .py file using AST extraction.
    Either can be None if not found.
    """
    content = py_path.read_text(encoding="utf-8", errors="replace")
    g = extract_globals(content)
    full = g.get("FLOW_FULL") if isinstance(g.get("FLOW_FULL"), list) else None
    test = g.get("FLOW_TEST") if isinstance(g.get("FLOW_TEST"), list) else None
    if full is None:
        # Fallback: try plain FLOW
        plain = g.get("FLOW")
        if isinstance(plain, list):
            full = plain
    return full, test


def _build_yaml_doc_from_globals(g: dict, full_flow: list | None, test_flow: list | None) -> dict:
    """Assemble the YAML document dict from extracted globals."""
    # Defaults section
    res = g.get("FORCE_RESOLUTION") or g.get("DEFAULT_RESOLUTION")
    defs: dict[str, Any] = {}
    if res:
        defs["resolution"] = list(res)
    for yaml_key, py_key, default in [
        ("backend",        "DEFAULT_BACKEND",        None),
        ("fps",            "DEFAULT_FPS",            None),
        ("steps",          "DEFAULT_STEPS",          None),
        ("cfg",            "DEFAULT_CFG",            None),
        ("duration",       "DEFAULT_DURATION",       None),
        ("blocks_to_swap",      "DEFAULT_BLOCKS_TO_SWAP",      None),
        ("frame_interpolation", "DEFAULT_FRAME_INTERPOLATION", None),
    ]:
        v = g.get(py_key)
        if v is not None:
            defs[yaml_key] = v

    doc: dict[str, Any] = {
        "project_folder": g.get("PROJECT_FOLDER", ""),
    }
    if defs:
        doc["defaults"] = defs

    use_test = bool(g.get("USE_TEST_FLOW", False))
    doc["use_test_flow"] = use_test

    # Linux / local backend paths
    lb: dict[str, Any] = {}
    for yaml_key, py_key in [
        ("config_path",           "CONFIG_PATH"),
        ("workflows_path",        "WORKFLOWS_PATH"),
        ("comfyui_output_folder", "COMFYUI_OUTPUT_FOLDER"),
        ("api_url",               "API_URL"),
    ]:
        v = g.get(py_key)
        if v is not None:
            lb[yaml_key] = v
    if lb:
        doc["linux_backend"] = lb

    if full_flow is not None:
        doc["flow"] = internal_flow_to_yaml(full_flow)
    if test_flow is not None:
        doc["flow_test"] = internal_flow_to_yaml(test_flow)

    return doc


class _LiteralStr(str):
    """Marker for strings that should be dumped as YAML literal blocks (|)."""


def _literal_representer(dumper: yaml.Dumper, data: _LiteralStr) -> yaml.ScalarNode:
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style="|")


# These keys always use | block style — even single-line — so they're easy to edit.
_FORCE_LITERAL_KEYS = {"pos", "neg"}


def _make_literal(val: Any, _key: str | None = None) -> Any:
    """
    Recursively wrap strings in _LiteralStr so PyYAML emits them with | style.
    - Multiline strings: always literal.
    - pos / neg fields: always literal (even one-liners) for easy hand-editing.
    """
    if isinstance(val, str):
        if "\n" in val or _key in _FORCE_LITERAL_KEYS:
            return _LiteralStr(val)
        return val
    if isinstance(val, list):
        return [_make_literal(v) for v in val]
    if isinstance(val, dict):
        return {k: _make_literal(v, _key=k) for k, v in val.items()}
    return val


# ── YAML pretty-printer ──────────────────────────────────────────────────────

_SECTION_LABEL: dict[str, str] = {
    "flow":      "FLOW — lista generacji",
    "flow_test": "FLOW_TEST — lista testowa",
}


def _beautify_yaml(text: str) -> str:
    """
    Post-process raw PyYAML output for human readability:

    1. Blank line before every top-level key   (separates: defaults / flow / …)
    2. Section comment block before flow: and flow_test:
    3. Blank line before every top-level list item  (separates flow entries)
    """
    lines = text.split("\n")
    result: list[str] = []

    for line in lines:
        # ── Classify this line ───────────────────────────────────────────
        is_top_key = (
            bool(line)
            and not line[0].isspace()
            and not line.startswith("#")
            and not line.startswith("-")
            and ":" in line
        )
        is_top_item = line.startswith("- ") or line == "-"

        # ── 1. Blank line before every top-level key ─────────────────────
        if is_top_key and result and result[-1] != "":
            result.append("")

        # ── 2. Section comment for flow / flow_test ───────────────────────
        if is_top_key:
            key_name = line.split(":")[0].strip()
            if key_name in _SECTION_LABEL:
                bar = "# " + "─" * 58
                result.append(bar)
                result.append(f"# {_SECTION_LABEL[key_name]}")
                result.append(bar)

        # ── 3. Blank line before top-level list items ────────────────────
        if is_top_item:
            # Find the last non-blank line already written
            prev_non_blank = next((r for r in reversed(result) if r != ""), "")
            # Don't add blank right after the section header key (e.g. "flow:")
            if prev_non_blank and not prev_non_blank.rstrip().endswith(":"):
                if result and result[-1] != "":
                    result.append("")

        result.append(line)

    return "\n".join(result)


def _yaml_dump(doc: dict) -> str:
    """Dump a dict to YAML text with literal block style and human-friendly spacing."""
    dumper = yaml.Dumper
    dumper.add_representer(_LiteralStr, _literal_representer)
    raw = yaml.dump(
        _make_literal(doc),
        Dumper=dumper,
        default_flow_style=False,
        allow_unicode=True,
        sort_keys=False,
        width=10_000,      # never wrap — long strings stay on one line until | kicks in
    )
    return _beautify_yaml(raw)


def migrate_py_to_yaml(py_path: Path, out_path: Path | None = None) -> Path:
    """
    Migrate a RUN_*.py file to a RUN_*.yaml file.

    Parameters
    ----------
    py_path : Path
        Path to the source .py file.
    out_path : Path | None
        Destination .yaml path.  Defaults to same dir/stem but .yaml.

    Returns
    -------
    Path
        Path to the written .yaml file.

    Raises
    ------
    FileNotFoundError
        If py_path does not exist.
    ValueError
        If no FLOW could be extracted from the .py file.
    """
    if not py_path.exists():
        raise FileNotFoundError(f"Python RUN file not found: {py_path}")

    if out_path is None:
        out_path = py_path.with_suffix(".yaml")

    content = py_path.read_text(encoding="utf-8", errors="replace")
    g = extract_globals(content)
    full_flow, test_flow = _get_both_flows(py_path)

    if full_flow is None and test_flow is None:
        raise ValueError(f"Could not extract any FLOW from {py_path.name}")

    doc = _build_yaml_doc_from_globals(g, full_flow, test_flow)

    # Validate before writing
    errors = validate_yaml_doc(doc)
    if errors:
        # Non-fatal: warn but still write (project_folder might be empty etc.)
        header = (
            f"# WARNING: validation issues found during migration:\n"
            + "".join(f"#   - {e}\n" for e in errors)
            + "#\n"
        )
    else:
        header = (
            f"# Migrated from: {py_path.name}\n"
            f"# Migration date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
            f"# Edit this file freely — regenerate .py with generate_py_from_yaml()\n#\n"
        )

    yaml_text = header + _yaml_dump(doc)
    out_path.write_text(yaml_text, encoding="utf-8")
    return out_path


def get_yaml_globals(yaml_path: Path) -> dict | None:
    """
    Return the non-flow sections of a YAML RUN file for the settings editor.
    Returns None if the file does not exist or cannot be parsed.
    """
    if not yaml_path.exists():
        return None
    try:
        doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    except Exception:
        return None
    if not isinstance(doc, dict):
        return None
    return {
        "project_folder":  doc.get("project_folder", ""),
        "use_test_flow":   bool(doc.get("use_test_flow", False)),
        "defaults":        dict(doc.get("defaults") or {}),
        "linux_backend":   dict(doc.get("linux_backend") or {}),
    }


def save_yaml_globals(yaml_path: Path, globals_data: dict) -> None:
    """
    Update non-flow sections (project_folder, defaults, linux_backend, use_test_flow)
    of a YAML RUN file without touching the flow lists.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ValueError("YAML document is not a mapping")

    allowed = {"project_folder", "defaults", "linux_backend", "use_test_flow"}
    for key in allowed:
        if key in globals_data:
            val = globals_data[key]
            # Remove section entirely when an empty dict/string is passed
            if val == "" or val == {} or val is None:
                doc.pop(key, None)
            else:
                doc[key] = val

    errors = validate_yaml_doc(doc)
    if errors:
        raise ValueError("YAML validation errors:\n" + "\n".join(f"  • {e}" for e in errors))

    header = (
        f"# {yaml_path.name}\n"
        f"# Edited: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# Edit this file freely — regenerate .py with generate_py_from_yaml()\n#\n"
    )
    yaml_path.write_text(header + _yaml_dump(doc), encoding="utf-8")


def create_run_from_globals(
    new_name: str,
    out_dir: Path,
    source_yaml: Path | None = None,
) -> Path:
    """
    Create a new RUN_*.yaml by cloning the global settings from *source_yaml*
    (project_folder, defaults, linux_backend) and leaving flow empty.

    If *source_yaml* is None or unreadable, sensible empty defaults are used.

    Parameters
    ----------
    new_name:
        Project name.  If it doesn't start with ``RUN_`` that prefix is added
        automatically.  ``.yaml`` extension is appended if missing.
    out_dir:
        Directory where the new file is created (normally RUNS_FOLDER).
    source_yaml:
        Optional path to the YAML file to copy globals from.

    Returns
    -------
    Path
        Path to the newly created .yaml file.

    Raises
    ------
    FileExistsError
        If a file with the computed name already exists.
    """
    # Normalise filename
    stem = new_name.strip()
    if not stem.upper().startswith("RUN_"):
        stem = f"RUN_{stem}"
    if not stem.endswith(".yaml"):
        stem = f"{stem}.yaml"

    out_path = out_dir / stem
    if out_path.exists():
        raise FileExistsError(f"Plik już istnieje: {stem}")

    # Read globals from source
    globals_data: dict = {}
    if source_yaml is not None and source_yaml.exists():
        try:
            raw = get_yaml_globals(source_yaml)
            if isinstance(raw, dict):
                globals_data = raw
        except Exception:
            pass

    # New projects only store project_folder + flow.
    # defaults and linux_backend come from app_config.yaml (global),
    # so we don't copy them — keeps new YAMLs minimal.
    doc: dict = {"project_folder": "", "use_test_flow": False, "flow": []}

    header = (
        f"# {stem}\n"
        f"# Created: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# Edit this file freely — regenerate .py with generate_py_from_yaml()\n#\n"
    )
    out_path.write_text(header + _yaml_dump(doc), encoding="utf-8")
    return out_path


def save_yaml_flow(yaml_path: Path, new_flow: list, flow_key: str = "flow") -> None:
    """
    Overwrite the 'flow' (or 'flow_test') list in a YAML RUN file.

    Parameters
    ----------
    yaml_path : Path
        The .yaml file to update.
    new_flow : list
        New flow items in *internal* format (chain items have chain_prefix + chain keys).
    flow_key : str
        Which key to update: 'flow' or 'flow_test'.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    if not isinstance(doc, dict):
        raise ValueError("YAML document is not a mapping")

    doc[flow_key] = internal_flow_to_yaml(new_flow)

    errors = validate_yaml_doc(doc)
    if errors:
        raise ValueError("YAML validation errors:\n" + "\n".join(f"  • {e}" for e in errors))

    header = (
        f"# {yaml_path.name}\n"
        f"# Edited: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# Edit this file freely — regenerate .py with generate_py_from_yaml()\n#\n"
    )
    yaml_path.write_text(header + _yaml_dump(doc), encoding="utf-8")


def reformat_yaml(yaml_path: Path) -> Path:
    """
    Re-parse an existing RUN_*.yaml and re-write it with the current pretty formatter.

    Useful after updating the formatter (new blank lines, | style, section headers)
    to apply the new style without losing any data.

    Returns the same path (file is overwritten in place).
    Raises FileNotFoundError / ValueError on problems.
    """
    if not yaml_path.exists():
        raise FileNotFoundError(f"YAML file not found: {yaml_path}")

    doc = yaml.safe_load(yaml_path.read_text(encoding="utf-8"))
    errors = validate_yaml_doc(doc)
    if errors:
        raise ValueError("YAML validation errors:\n" + "\n".join(f"  • {e}" for e in errors))

    header = (
        f"# {yaml_path.name}\n"
        f"# Reformatted: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n"
        f"# Edit this file freely — regenerate .py with generate_py_from_yaml()\n#\n"
    )
    yaml_path.write_text(header + _yaml_dump(doc), encoding="utf-8")
    return yaml_path
